#cloud-config
apt_update: true
packages:
  - curl
  - git
  - vim
  - ruby-full
  - nginx
  - python-pip
runcmd:
  - gem install gist
  - sed -ie 's/Port 22/Port 443/' /etc/ssh/sshd_config
  - service ssh restart
  - pip install -U youtube_dl
  - cd
  - git clone http://github.com/icyflame/dotfiles.git
  - cd dotfiles
  - bash bootstrap.sh digitalocean
